# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-22 16:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20190622_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('boss', models.CharField(max_length=500)),
                ('jobtitle', models.CharField(max_length=255)),
                ('rating', models.IntegerField(default=50)),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
                ('notes', models.TextField()),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('dob', models.DateField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='How_well_known',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='how_well_known', to='employees.Employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='how_well_known', to='users.User')),
            ],
        ),
    ]
