# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-04 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_preferred_fname'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_image',
            name='title',
            field=models.CharField(default='Employee Photo', max_length=255),
        ),
        migrations.AlterField(
            model_name='employee_image',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
