# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-04 21:01
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_auto_20190704_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_image',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
